{
 "title": "Fraud_Detection_Data_Engineering_System",
 "time": { "from": "now-5y", "to": "now" },
 "panels": [
  {
   "title": "High-Risk Threat Exposure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    COUNT(*) AS \"High-Risk Alerts\",\r\n    ROUND(SUM(f.transaction_amount)::numeric, 2) AS \"Total Exposure ($)\"\r\nFROM fact_fraud_inference f\r\nWHERE f.xgboost_probability > 0.9;"
    }
   ]
  },
  {
   "title": "Model Score Distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CAST(TRUNC(xgboost_probability::numeric, 1) AS TEXT) AS \"Score Bucket\",\r\n    COUNT(*) AS \"Count\"\r\nFROM fact_fraud_inference\r\nWHERE xgboost_probability >= 0.1\r\n  AND $__timeFilter(inference_timestamp)\r\nGROUP BY TRUNC(xgboost_probability::numeric, 1)\r\nORDER BY \"Score Bucket\";"
    }
   ]
  },
  {
   "title": "Fraud Rate Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    dt.full_timestamp AS \"time\",\r\n    ROUND((SUM(f.is_fraud)::numeric / COUNT(*) * 100), 2) AS \"Fraud Rate %\"\r\nFROM fact_fraud_inference f\r\nJOIN dim_time dt ON f.time_id = dt.time_id\r\nGROUP BY dt.full_timestamp\r\nORDER BY dt.full_timestamp;"
    }
   ]
  },
  {
   "title": "Transaction Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    inference_timestamp AS \"time\",\r\n    COUNT(*) AS \"Total Transactions\"\r\nFROM fact_fraud_inference\r\nGROUP BY inference_timestamp\r\nORDER BY inference_timestamp;"
    }
   ]
  }
 ]
}